-- Artly Social - schema và dữ liệu mẫu cho PostgreSQL 17.
-- Chạy file bằng psql. File có thể chạy lại an toàn nhờ IF NOT EXISTS
-- và ON CONFLICT.

\set ON_ERROR_STOP on

-- Khi chạy thủ công từ database "postgres" hoặc "template1", mặc định tạo
-- database artly_social. Nếu Docker đã kết nối vào POSTGRES_DB tùy chỉnh thì
-- giữ chính database hiện tại, không hardcode tên database của container.
SELECT CASE
  WHEN current_database() IN ('postgres', 'template1') THEN 'artly_social'
  ELSE current_database()
END AS artly_database
\gset

SELECT format(
  'CREATE DATABASE %I WITH ENCODING %L TEMPLATE template0',
  :'artly_database',
  'UTF8'
)
WHERE NOT EXISTS (
  SELECT 1
  FROM pg_database
  WHERE datname = :'artly_database'
)
\gexec

\connect :artly_database

SET client_encoding = 'UTF8';
SET TIME ZONE 'UTC';
SET search_path TO public;

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(50) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  avatar_url VARCHAR(2048),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT users_username_unique UNIQUE (username),
  CONSTRAINT chk_users_role
    CHECK (role IN ('STUDENT', 'TEACHER')),
  CONSTRAINT chk_users_username_format
    CHECK (username ~ '^[a-z0-9._-]{3,50}$'),
  CONSTRAINT chk_users_display_name_length
    CHECK (CHAR_LENGTH(TRIM(display_name)) BETWEEN 1 AND 100),
  CONSTRAINT chk_users_avatar_url
    CHECK (
      avatar_url IS NULL
      OR avatar_url LIKE 'http://%'
      OR avatar_url LIKE 'https://%'
    )
);

CREATE TABLE IF NOT EXISTS topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  slug VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  normalized_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT topics_slug_unique UNIQUE (slug),
  CONSTRAINT topics_normalized_name_unique UNIQUE (normalized_name),
  CONSTRAINT chk_topics_name_length
    CHECK (CHAR_LENGTH(TRIM(name)) BETWEEN 1 AND 100),
  CONSTRAINT chk_topics_normalized_name_length
    CHECK (CHAR_LENGTH(TRIM(normalized_name)) BETWEEN 1 AND 100),
  CONSTRAINT chk_topics_slug_format
    CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

CREATE TABLE IF NOT EXISTS topic_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  topic_id BIGINT NOT NULL,
  alias VARCHAR(100) NOT NULL,
  normalized_alias VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT topic_aliases_normalized_alias_unique UNIQUE (normalized_alias),
  CONSTRAINT fk_topic_aliases_topic
    FOREIGN KEY (topic_id) REFERENCES topics (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_topic_aliases_length
    CHECK (
      CHAR_LENGTH(TRIM(alias)) BETWEEN 1 AND 100
      AND CHAR_LENGTH(TRIM(normalized_alias)) BETWEEN 1 AND 100
    )
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  caption TEXT NOT NULL,
  image_url VARCHAR(2048) NOT NULL,
  exam_name VARCHAR(160),
  status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_posts_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_posts_status
    CHECK (status IN ('PUBLISHED', 'ARCHIVED')),
  CONSTRAINT chk_posts_title_length
    CHECK (CHAR_LENGTH(TRIM(title)) BETWEEN 1 AND 120),
  CONSTRAINT chk_posts_caption_length
    CHECK (CHAR_LENGTH(TRIM(caption)) BETWEEN 1 AND 2000),
  CONSTRAINT chk_posts_image_url
    CHECK (image_url LIKE 'http://%' OR image_url LIKE 'https://%'),
  CONSTRAINT chk_posts_exam_name_length
    CHECK (
      exam_name IS NULL
      OR CHAR_LENGTH(TRIM(exam_name)) BETWEEN 1 AND 160
    )
);

CREATE TABLE IF NOT EXISTS post_topics (
  post_id BIGINT NOT NULL,
  topic_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, topic_id),
  CONSTRAINT fk_post_topics_post
    FOREIGN KEY (post_id) REFERENCES posts (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_post_topics_topic
    FOREIGN KEY (topic_id) REFERENCES topics (id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'LIKE',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT reactions_post_user_unique UNIQUE (post_id, user_id),
  CONSTRAINT fk_reactions_post
    FOREIGN KEY (post_id) REFERENCES posts (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_reactions_user
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_reactions_type
    CHECK (type IN ('LIKE', 'LOVE', 'CLAP'))
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  body TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_messages_sender
    FOREIGN KEY (sender_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_messages_receiver
    FOREIGN KEY (receiver_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_messages_body_length
    CHECK (CHAR_LENGTH(TRIM(body)) BETWEEN 1 AND 2000),
  CONSTRAINT chk_messages_is_read
    CHECK (is_read IN (FALSE, TRUE))
);

-- Các index phục vụ bảng tin, tra cứu chủ đề, reaction và hội thoại.
CREATE INDEX IF NOT EXISTS users_role_index
  ON users (role);

CREATE INDEX IF NOT EXISTS topics_name_index
  ON topics (name);

CREATE INDEX IF NOT EXISTS topic_aliases_topic_index
  ON topic_aliases (topic_id);

CREATE INDEX IF NOT EXISTS posts_status_created_id_index
  ON posts (status, created_at, id);

CREATE INDEX IF NOT EXISTS posts_user_created_id_index
  ON posts (user_id, created_at, id);

CREATE INDEX IF NOT EXISTS post_topics_topic_post_index
  ON post_topics (topic_id, post_id);

CREATE INDEX IF NOT EXISTS reactions_user_created_index
  ON reactions (user_id, created_at);

CREATE INDEX IF NOT EXISTS messages_sender_receiver_created_index
  ON messages (sender_id, receiver_id, created_at, id);

CREATE INDEX IF NOT EXISTS messages_receiver_sender_created_index
  ON messages (receiver_id, sender_id, created_at, id);

CREATE INDEX IF NOT EXISTS messages_receiver_unread_index
  ON messages (receiver_id, is_read, created_at);

-- PostgreSQL không có ON UPDATE CURRENT_TIMESTAMP ở định nghĩa cột.
-- Trigger dùng chung này duy trì updated_at cho mọi bảng có thể cập nhật.
CREATE OR REPLACE FUNCTION artly_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS topics_set_updated_at ON topics;
CREATE TRIGGER topics_set_updated_at
  BEFORE UPDATE ON topics
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS topic_aliases_set_updated_at ON topic_aliases;
CREATE TRIGGER topic_aliases_set_updated_at
  BEFORE UPDATE ON topic_aliases
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS posts_set_updated_at ON posts;
CREATE TRIGGER posts_set_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS post_topics_set_updated_at ON post_topics;
CREATE TRIGGER post_topics_set_updated_at
  BEFORE UPDATE ON post_topics
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS reactions_set_updated_at ON reactions;
CREATE TRIGGER reactions_set_updated_at
  BEFORE UPDATE ON reactions
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

DROP TRIGGER IF EXISTS messages_set_updated_at ON messages;
CREATE TRIGGER messages_set_updated_at
  BEFORE UPDATE ON messages
  FOR EACH ROW
  EXECUTE FUNCTION artly_set_updated_at();

-- Tài khoản demo: dùng id 1, 2 hoặc 3 trong header X-User-ID.
INSERT INTO users
  (id, username, display_name, role, avatar_url)
VALUES
  (
    1,
    'minh.an',
    'Trần Minh An',
    'STUDENT',
    'https://i.pravatar.cc/256?img=12'
  ),
  (
    2,
    'co.lan',
    'Cô Nguyễn Hoài Lan',
    'TEACHER',
    'https://i.pravatar.cc/256?img=47'
  ),
  (
    3,
    'phuong.thao',
    'Nguyễn Phương Thảo',
    'STUDENT',
    'https://i.pravatar.cc/256?img=32'
  )
ON CONFLICT (id) DO UPDATE SET
  username = EXCLUDED.username,
  display_name = EXCLUDED.display_name,
  role = EXCLUDED.role,
  avatar_url = EXCLUDED.avatar_url;

INSERT INTO topics
  (id, slug, name, normalized_name)
VALUES
  (1, 'phong-canh', 'Phong cảnh', 'phong canh'),
  (2, 'chan-dung', 'Chân dung', 'chan dung'),
  (3, 'moi-truong', 'Môi trường', 'moi truong'),
  (4, 'hoa-binh', 'Hòa bình', 'hoa binh'),
  (5, 'di-san-van-hoa', 'Di sản văn hóa', 'di san van hoa'),
  (6, 'uoc-mo', 'Ước mơ', 'uoc mo')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  normalized_name = EXCLUDED.normalized_name;

INSERT INTO topic_aliases
  (id, topic_id, alias, normalized_alias)
VALUES
  (1, 1, 'Cảnh vật', 'canh vat'),
  (2, 1, 'Landscape', 'landscape'),
  (3, 2, 'Vẽ người', 've nguoi'),
  (4, 2, 'Portrait', 'portrait'),
  (5, 3, 'Bảo vệ môi trường', 'bao ve moi truong'),
  (6, 3, 'Environment', 'environment'),
  (7, 4, 'Tình bạn', 'tinh ban'),
  (8, 4, 'Peace', 'peace'),
  (9, 5, 'Di sản', 'di san'),
  (10, 5, 'Heritage', 'heritage'),
  (11, 6, 'Giấc mơ', 'giac mo'),
  (12, 6, 'Dream', 'dream')
ON CONFLICT (id) DO UPDATE SET
  topic_id = EXCLUDED.topic_id,
  alias = EXCLUDED.alias,
  normalized_alias = EXCLUDED.normalized_alias;

INSERT INTO posts
  (
    id,
    user_id,
    title,
    caption,
    image_url,
    exam_name,
    status
  )
VALUES
  (
    1,
    1,
    'Mầm xanh tương lai',
    'Bài vẽ màu nước về những bàn tay cùng nâng niu một mầm cây xanh.',
    'http://localhost:5173/demo-art/mam-xanh-tuong-lai.png',
    'Sắc màu xanh 2026',
    'PUBLISHED'
  ),
  (
    2,
    3,
    'Hòa bình trong em',
    'Chim bồ câu và những bàn tay nhiều sắc màu thể hiện tình bạn học đường.',
    'http://localhost:5173/demo-art/hoa-binh-trong-em.png',
    'Thiếu nhi Việt Nam vẽ hòa bình',
    'PUBLISHED'
  ),
  (
    3,
    1,
    'Di sản quê em',
    'Em chọn phố cổ Hội An, đèn lồng và dòng sông làm cảm hứng cho bài thi.',
    'http://localhost:5173/demo-art/di-san-que-em.png',
    'Di sản trong mắt em',
    'PUBLISHED'
  ),
  (
    4,
    3,
    'Chân dung người truyền cảm hứng',
    'Bài chân dung cô giáo mỹ thuật đã giúp em tự tin hơn với màu sắc.',
    'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=80',
    'Người thầy trong em',
    'PUBLISHED'
  ),
  (
    5,
    1,
    'Thành phố trên mây',
    'Em tưởng tượng một thành phố xanh có những khu vườn bay giữa bầu trời.',
    'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1200&q=80',
    'Ước mơ của em',
    'PUBLISHED'
  )
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  title = EXCLUDED.title,
  caption = EXCLUDED.caption,
  image_url = EXCLUDED.image_url,
  exam_name = EXCLUDED.exam_name,
  status = EXCLUDED.status;

INSERT INTO post_topics (post_id, topic_id)
VALUES
  (1, 1),
  (1, 3),
  (2, 4),
  (3, 5),
  (4, 2),
  (5, 1),
  (5, 6)
ON CONFLICT (post_id, topic_id) DO NOTHING;

INSERT INTO reactions
  (id, post_id, user_id, type)
VALUES
  (1, 1, 2, 'LOVE'),
  (2, 1, 3, 'CLAP'),
  (3, 2, 1, 'LIKE'),
  (4, 3, 2, 'LOVE'),
  (5, 4, 1, 'CLAP'),
  (6, 5, 2, 'LIKE')
ON CONFLICT (id) DO UPDATE SET
  post_id = EXCLUDED.post_id,
  user_id = EXCLUDED.user_id,
  type = EXCLUDED.type;

INSERT INTO messages
  (id, sender_id, receiver_id, body, is_read)
VALUES
  (
    1,
    1,
    2,
    'Cô xem giúp em phần phối màu của bài Mầm xanh tương lai với ạ.',
    TRUE
  ),
  (
    2,
    2,
    1,
    'Em thử tăng độ tương phản ở vùng tiền cảnh nhé, bố cục đang rất tốt.',
    TRUE
  ),
  (
    3,
    3,
    2,
    'Cô ơi, bài Hòa bình trong em của em đã đủ rõ chủ đề chưa ạ?',
    TRUE
  ),
  (
    4,
    2,
    3,
    'Chủ đề rất rõ rồi em. Em có thể làm nổi bật chim bồ câu thêm một chút.',
    FALSE
  )
ON CONFLICT (id) DO UPDATE SET
  sender_id = EXCLUDED.sender_id,
  receiver_id = EXCLUDED.receiver_id,
  body = EXCLUDED.body,
  is_read = EXCLUDED.is_read;

-- Seed dùng id cố định nên cần đưa các identity sequence tới giá trị lớn nhất.
-- Tham số thứ ba giúp lần nextval tiếp theo trả về MAX(id) + 1.
SELECT setval(
  pg_get_serial_sequence('public.users', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM users;

SELECT setval(
  pg_get_serial_sequence('public.topics', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM topics;

SELECT setval(
  pg_get_serial_sequence('public.topic_aliases', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM topic_aliases;

SELECT setval(
  pg_get_serial_sequence('public.posts', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM posts;

SELECT setval(
  pg_get_serial_sequence('public.reactions', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM reactions;

SELECT setval(
  pg_get_serial_sequence('public.messages', 'id'),
  COALESCE(MAX(id), 1),
  MAX(id) IS NOT NULL
)
FROM messages;

COMMIT;
